version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "JrInLab-Secrets-Prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b4ywvnf6cm55"
s3_prefix = "JrInLab-Secrets-Prod"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\" RepositoryUrl=\"https://github.com/ra-jeev/JrInLab\" DemoMsgWebhook=\"NA\" ContactMsgWebhook=\"NA\""
image_repositories = []

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "JrInLab-Secrets-Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b4ywvnf6cm55"
s3_prefix = "JrInLab-Secrets-Dev"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\" RepositoryUrl=\"https://github.com/ra-jeev/JrInLab\" DemoMsgWebhook=\"\" ContactMsgWebhook=\"\""
image_repositories = []
