AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Repository URL and Access Token for JrInLab application

Parameters:
  Stage:
    Type: String
    Description: Backend stage to deploy resources to - dev/staging/prod
    AllowedValues: ['staging', 'prod', 'dev']
    ConstraintDescription: allowed values dev/staging/prod

  RepositoryUrl:
    Type: String
    Description: Project's Repository URL

  GithubAccessToken:
    Type: String
    Description: Repository's Access Token
    NoEcho: true

  MailgunApiKey:
    Type: String
    Description: Mailgun's Api Key
    NoEcho: true

  DemoMsgWebhook:
    Type: String
    Description: Discord webhook url, where incoming demo requests will be posted

  ContactMsgWebhook:
    Type: String
    Description: Discord webhook url, where website's contact form messages will be posted

Resources:
  RepoSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Stage}/JrInLab/RepoSecrets
      Description: Repository URL and the corresponding Github Access Token for use with AWS Amplify
      SecretString: !Sub '{"Url":"${RepositoryUrl}","AccessToken":"${GithubAccessToken}"}'

  DiscordSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Stage}/JrInLab/DiscordSecrets
      Description: Discord webhook URLs
      SecretString: !Sub '{"DemoHook":"${DemoMsgWebhook}","ContactHook":"${ContactMsgWebhook}"}'

  MailgunSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Stage}/JrInLab/MailgunSecrets
      Description: Mailgun secrets and related settings
      SecretString: !Sub '{"ApiKey":"${MailgunApiKey}"}'
