import colors from 'vuetify/es5/util/colors'
import {
  mdiAccountOutline,
  mdiAccountPlus,
  mdiAlertDecagram,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiCalendar,
  mdiCalendarCheck,
  mdiCalendarQuestion,
  mdiCastEducation,
  mdiCheck,
  mdiChevronDown,
  mdiChevronDownCircleOutline,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClock,
  mdiClose,
  mdiCloseBox,
  mdiCloudUpload,
  mdiCommentQuote,
  mdiCreation,
  mdiCreditCardOutline,
  mdiDelete,
  mdiDotsVertical,
  mdiEmail,
  mdiEmailOutline,
  mdiExitToApp,
  mdiEye,
  mdiEyeOff,
  mdiFaceAgent,
  mdiFacebook,
  mdiFileCog,
  mdiFilter,
  mdiFormatQuoteOpen,
  mdiHand,
  mdiHandshake,
  mdiHelpRhombus,
  mdiLaptop,
  mdiMagnify,
  mdiMapMarker,
  mdiMenuDown,
  mdiMessageTextOutline,
  mdiOpenInNew,
  mdiPlay,
  mdiPencil,
  mdiPhone,
  mdiPhoneOutline,
  mdiPipeDisconnected,
  mdiPlus,
  mdiRefresh,
  mdiSale,
  mdiSend,
  mdiShieldCheck,
  mdiTableAccount,
  mdiTeach,
  mdiText,
  mdiViewDashboard,
  mdiWeb,
  mdiWhatsapp,
  mdiYoutube,
} from '@mdi/js'

export default function () {
  return {
    icons: {
      iconfont: 'mdiSvg',
      values: {
        mdiAccountOutline,
        mdiAccountPlus,
        mdiAlertDecagram,
        mdiArrowLeft,
        mdiArrowRight,
        mdiArrowUp,
        mdiCalendar,
        mdiCalendarCheck,
        mdiCalendarQuestion,
        mdiCastEducation,
        mdiCheck,
        mdiChevronDown,
        mdiChevronDownCircleOutline,
        mdiChevronLeft,
        mdiChevronRight,
        mdiChevronUp,
        mdiClock,
        mdiClose,
        mdiCloseBox,
        mdiCloudUpload,
        mdiCommentQuote,
        mdiCreation,
        mdiCreditCardOutline,
        mdiDelete,
        mdiDotsVertical,
        mdiEmail,
        mdiEmailOutline,
        mdiExitToApp,
        mdiEye,
        mdiEyeOff,
        mdiFaceAgent,
        mdiFacebook,
        mdiFileCog,
        mdiFilter,
        mdiFormatQuoteOpen,
        mdiHand,
        mdiHandshake,
        mdiHelpRhombus,
        mdiLaptop,
        mdiMagnify,
        mdiMapMarker,
        mdiMenuDown,
        mdiMessageTextOutline,
        mdiOpenInNew,
        mdiPipeDisconnected,
        mdiPlay,
        mdiPencil,
        mdiPhone,
        mdiPhoneOutline,
        mdiPlus,
        mdiRefresh,
        mdiSale,
        mdiSend,
        mdiShieldCheck,
        mdiTableAccount,
        mdiTeach,
        mdiText,
        mdiViewDashboard,
        mdiWeb,
        mdiWhatsapp,
        mdiYoutube,
      },
    },
    theme: {
      dark: false,
      themes: {
        light: {
          primary: '#6C63FF',
          secondary: '#F16334', // '#00D09C',
          accent: colors.deepOrange.lighten1, // colors.orange.darken2
        },
        dark: {
          primary: colors.blue.darken2,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3,
        },
      },
    },
  }
}
