import colors from 'vuetify/es5/util/colors'
import {
  mdiAccountCircle,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiCake,
  mdiCheckCircle,
  mdiCloseCircle,
  mdiCloudUpload,
  mdiContentCopy,
  mdiContentSave,
  mdiDelete,
  mdiDotsVertical,
  mdiEmail,
  mdiExitToApp,
  mdiFolderFile,
  mdiInformation,
  mdiMapMarker,
  mdiMenu,
  mdiOpenInNew,
  mdiPaperclip,
  mdiPencil,
  mdiPlus,
  mdiRocketLaunch,
  mdiShare,
  mdiShieldAlert,
  mdiShieldCheck,
  mdiUpdate,
  mdiWeb,
  mdiWebOff,
} from '@mdi/js'

export default function () {
  return {
    icons: {
      iconfont: 'mdiSvg',
      values: {
        mdiAccountCircle,
        mdiArrowLeft,
        mdiArrowRight,
        mdiArrowUp,
        mdiCake,
        mdiCheckCircle,
        mdiCloseCircle,
        mdiCloudUpload,
        mdiContentCopy,
        mdiContentSave,
        mdiDelete,
        mdiDotsVertical,
        mdiEmail,
        mdiExitToApp,
        mdiFolderFile,
        mdiInformation,
        mdiMapMarker,
        mdiMenu,
        mdiOpenInNew,
        mdiPencil,
        mdiPlus,
        mdiPaperclip,
        mdiRocketLaunch,
        mdiShare,
        mdiShieldAlert,
        mdiShieldCheck,
        mdiUpdate,
        mdiWeb,
        mdiWebOff,
      },
    },
    theme: {
      dark: false,
      themes: {
        light: {
          primary: '#FF5E29', // '#F27059'
          secondary: '#F7B801', // '#FFC600, '#00D09C',
          accent: '#7678ED', // '#3a6ea5', // '#2e77ae', // '#3a6ea5', '#004e98', '#ebebeb'
        },
        dark: {
          primary: colors.blue.darken2,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3,
        },
      },
    },
  }
}
